import Project.Chapter19.Exercises.Exercise01
import Project.Chapter19.Exercises.Exercise02
import Project.Chapter19.Exercises.Exercise03
import Project.Chapter19.Exercises.Exercise05
import Project.Chapter19.Exercises.Exercise04
import Project.Chapter19.Exercises.Exercise08
import Project.Chapter19.Exercises.Exercise06
import Project.Chapter19.Exercises.Exercise07
import Project.Chapter13.Exercises.Exercise01
import Project.Chapter13.Exercises.Exercise02
import Project.Chapter13.Exercises.Exercise03
import Project.Chapter13.Exercises.Exercise04
import Project.Chapter13.Exercises.Exercise06
import Project.Chapter13.Exercises.Exercise07
import Project.Chapter01.Exercises.Exercise01
import Project.Chapter01.Exercises.Exercise02
import Project.Chapter01.Exercises.Exercise05
import Project.Chapter01.Exercises.Exercise06
import Project.Chapter01.Exercises.Exercise07
import Project.Chapter22.Exercise01
import Project.Chapter02.Exercises.Exercise01
import Project.Chapter02.Exercises.Exercise02
import Project.Chapter02.Exercises.Exercise03
import Project.Chapter02.Exercises.Exercise05
import Project.Chapter02.Exercises.Exercise04
import Project.Chapter02.Exercises.Exercise08
import Project.Chapter02.Exercises.Exercise06
import Project.Chapter02.Exercises.Exercise07
import Project.Chapter08.Exercises.Exercise01
import Project.Chapter08.Exercises.Exercise09
import Project.Chapter08.Exercises.Exercise05
import Project.Chapter08.Exercises.Exercise06
import Project.Chapter23.Exercises.Exercise01
import Project.Chapter23.Exercises.Exercise02
import Project.Chapter23.Exercises.Exercise09
import Project.Chapter23.Exercises.Exercise03
import Project.Chapter23.Exercises.Exercise05
import Project.Chapter23.Exercises.Exercise04
import Project.Chapter23.Exercises.Exercise08
import Project.Chapter23.Exercises.Exercise06
import Project.Chapter23.Exercises.Exercise07

